WebMVC/Controllers/EjemploController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMVC.Controllers
{
    public class EjemploController : Controller
    {
        public ActionResult Sesion()
        {
            ML.Usuario usus = new ML.Usuario();
            Session["nombreSesion"] = usus; //puede guardar cualquier tipo de dato (Primitivo o Complejo)
            Session["nombreSesion"] = null; //limpiar sesion

            if (Session["nombreSesion"]!= null)
            {


            } else //session viene vacia
            {

            }
            return View();
        }

        // GET: Ejemplo
        public ActionResult Form(int? id)
        {
            ML.Usuario usuario = new ML.Usuario();
            usuario.Imagen = "";
            //Instanciamos todas las referencias
            usuario.Rol = new ML.Rol();
            usuario.Direccion = new ML.Direccion();
            usuario.Direccion.Colonia = new ML.Colonia();
            usuario.Direccion.Colonia.Municipio = new ML.Municipio();
            usuario.Direccion.Colonia.Municipio.Estado = new ML.Estado();
            usuario.Direccion.Colonia.Municipio.Estado.Pais = new ML.Pais();

            ML.Result resultRol = BL.Rol.GetAll();
            //Obtenemos los paises
            ML.Result resultPais = BL.Pais.GetAll();

            if (id == null) //Agregar
            {
                //paso los paises
                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPais.Objects;
                usuario.Rol.Roles = resultRol.Objects;
            }
            else //Update
            {
                ML.Result result = BL.Usuario.GetByIdEF(id.Value);

                usuario = (ML.Usuario)result.Object;
                //Pasamos la lista de roles
                usuario.Rol.Roles = resultRol.Objects;


                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPais.Objects;

                usuario.Direccion.Colonia.Municipio.Estado.Estados = BL.Estado.GetByIdPais(usuario.Direccion.Colonia.Municipio.Estado.Pais.IdPais).Objects;

                //usuario.Direccion.Colonia.Municipio.Muncipios = BL.Municipio.GetByIdEstado(usuario.Direccion.Colonia.Municipio.Estado.IdEstado).Objects;

                return View(usuario);
            }

            return View(usuario);
        }

        public ActionResult GetAll()
        {

            ML.Usuario usuario = new ML.Usuario();

            ML.Result result = BL.Usuario.GetAllEF(usuario);

            if (result.Correct)
            {
                usuario.Usuarios = result.Objects.ToList();
                return View(usuario);
            }
            else
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult GetAll(ML.Usuario usuario)
        {
            if (usuario.Nombre == null)
            {
                usuario.Nombre = "";
            }
            else
            {
                usuario.Nombre = usuario.Nombre;
            }

            usuario.Nombre = (usuario.Nombre == null) ? usuario.Nombre = "" : usuario.Nombre;

            ML.Result result = BL.Usuario.GetAllEF(usuario);

            if (result.Correct)
            {
                usuario.Usuarios = result.Objects.ToList();
                return View(usuario);
            }
            else
            {
                return View();
            }

        }


        [HttpPost]
        public ActionResult Form(ML.Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["Imagen"];
                if (file.ContentLength > 0)
                {
                    usuario.Imagen = ConvertirABase64(file);
                }


                //resto del codigo para add
            } else
            {
                var roles = BL.Rol.GetAll2();
                var pais = BL.Pais.GetAll2();
                var estado = BL.Estado.GetByIdPais(usuario.Direccion.Colonia.Municipio.Estado.Pais.IdPais);
                var municipio = BL.Municipio.GetByIdEstado2(usuario.Direccion.Colonia.Municipio.Estado.IdEstado);
                var colonia = BL.Colonia.ColoniaGetByIdMunicipio2(usuario.Direccion.Colonia.Municipio.IdMunicipio);

                usuario.Rol.Roles = roles.Item3;
                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = pais.Item3;
                usuario.Direccion.Colonia.Municipio.Estado.Estados = estado.Objects;
                usuario.Direccion.Colonia.Municipio.Muncipios = municipio.Item3;
                usuario.Direccion.Colonia.Colonias = colonia.Item3;

                return View(usuario);
            }



            return View();
        }

        [HttpPost]
        public JsonResult EstadoGetByIdPais(int IdPais)
        {
            ML.Result result = BL.Estado.GetByIdPais(IdPais);
            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult MunicipioGetByIdEstado(int IdEstado)
        {
            ML.Result result = BL.Municipio.GetByIdEstado(IdEstado);
            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ColoniaGetByIdMunicipio(int IdMunicipio)
        {
            ML.Result result = BL.Colonia.ColoniaGetByIdMunicipio(IdMunicipio);
            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        public string ConvertirABase64(HttpPostedFileBase Foto)
        {
            System.IO.BinaryReader reader = new System.IO.BinaryReader(Foto.InputStream);
            byte[] data = reader.ReadBytes((int)Foto.ContentLength);
            string imagen = Convert.ToBase64String(data);
            return imagen;
        }

        [HttpPost]
        public JsonResult CambiarStatus(int IdUsuario, bool Status)
        {
            var result = BL.Usuario.CambioStatus(IdUsuario, Status);
            if (result.Item1)
            {
                return Json(result.Item1, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(result.Item2, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

//BOXING -- almacenar cualquier tipo de dato dentro de un Object
//UNBOXING -- extraer cualquier tipo de dato desde un Object

WebMVC/Views/Ejemplo/GetAll.cshtml
@model ML.Usuario

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
@Scripts.Render("~/bundles/jquery")
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>

<h2 class="text-center">Usuarios Registrados</h2>
<hr />

@if (Model.Usuarios != null)
{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <div class="table-responsive mb-4">
        <table class="table table-striped table-bordered table-hover" id="usuarioTabla">
            <thead class="text-center bg-primary text-white">
                <tr class="align-middle">

                    <th class="col">Status</th>
                    <th class="col">Imagen Usuario</th>
                    <th class="col">Nombre</th>
                    <th class="col">Apellido Paterno</th>
                    <th class="col">Apellido Materno</th>
                    <th class="col">Email</th>
                    <th class="col">Sexo</th>
                    <th class="col">Teléfono</th>
                    <th class="col">Celular</th>
                    <th class="col">Fecha Nacimiento</th>
                    <th class="col">CURP</th>
                    <th class="col">Calle</th>
                    <th class="col">CP</th>
                    <th class="col">Colonia</th>
                    <th class="col">Municipio</th>
                    <th class="col">Estado</th>
                    <th class="col">Pais</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody class="text-center">
                @foreach (ML.Usuario usuario in Model.Usuarios)
                {




                    <tr class="align-middle">
                        @if (usuario.Status)
                        {
                            <td>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked onchange="CambiarStatus('@usuario.IdUsuario', this)">
                                </div>

                            </td>
                        }
                        else
                        {
                            <td>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" onchange="CambiarStatus('@usuario.IdUsuario', this)"> 
                                </div>

                            </td>
                        }

                        @if (usuario.Imagen != null || usuario.Imagen == "")
                        {
                            <td>
                                <img id="img" src="data:image/*;base64,@usuario.Imagen" width="40" height="40" />
                            </td>
                        }
                        else
                        {
                            <td>
                                <img id="img" src="https://png.pngtree.com/png-vector/20220608/ourlarge/pngtree-faceless-user-anonymous-unknown-icon-png-image_4816463.png" width="40" height="40" />
                            </td>
                        }

                        @*<td>@usuario.IdUsuario</td>*@
                        <td>@usuario.Nombre</td>
                        <td>@usuario.ApellidoPaterno</td>
                        <td>@usuario.ApellidoMaterno</td>
                        <td>@usuario.Email</td>
                        @*<td>@usuario.Password</td>*@
                        <td>@usuario.Sexo</td>
                        <td>@usuario.Telefono</td>
                        <td>@usuario.Celular</td>
                        <td>@usuario.FechaNacimiento.ToString("dd/MM/yyyy")</td>
                        <td>@usuario.CURP</td>
                        @*<td>@usuario.Rol.idRol</td>*@

                        <td>@usuario.Direccion.Calle</td>
                        <td>@usuario.Direccion.Colonia.CodigoPostal</td>
                        <td>@usuario.Direccion.Colonia.Nombre</td>
                        <td>@usuario.Direccion.Colonia.Municipio.Nombre</td>
                        <td>@usuario.Direccion.Colonia.Municipio.Estado.Nombre</td>
                        <td>@usuario.Direccion.Colonia.Municipio.Estado.Pais.Nombre</td>

                        @*@if (usuario.Rol.Nombre == "Admin")
                            {
                                <td class="text-success">@usuario.Rol.Nombre</td>

                            }
                            else
                            {
                                <td style="color:orangered">@usuario.Rol.Nombre</td>

                            }*@

                        <td><a class="btn btn-outline-secondary m-1" href="@Url.Action("Form", "Ejemplo", new {id = usuario.IdUsuario})"><i class="fa-solid fa-pen-to-square fa-flip-horizontal fa-lg" style="color: #007bff;"></i></a></td>
                        <td>
                            <a class="btn btn-outline-secondary m-1" href="@Url.Action("Delete", "Ejemplo", new {id=usuario.IdUsuario})"
                               onclick="return confirm('¿Estás seguro de que deseas eliminar este usuario?')">
                                <i class="fa-sharp fa-solid fa-trash fa-lg" style="color: #dc3545;"></i>
                            </a>
                        </td>


                    </tr>

                }
            </tbody>
        </table>
    </div>

    <div class="text-center">
        <a href="@Url.Action("Form", "Ejemplo")" class="btn btn-success text-center">Agregar Usuario</a>
    </div>
}


<script>


    function CambiarStatus(idUsuario, input) {
        var valor = input.checked;
        $.ajax({
            url: '@Url.Action("CambiarStatus")',
            datatype: 'JSON',
            type: 'POST',
            data: { IdUsuario: idUsuario, Status: valor },
            success: function (result) {
            },
            error: function (result) {
                alert('Error en la conexion')
            }
        })
    }







    //let table = new DataTable('#usuarioTabla', {
    //    reponsive: true,
    //    "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "Todos"]],
    //    searching: false,
    //    language: {
    //        url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
    //    },
    //});
</script>